"""data-processor - Custom MCP-native Agent.

A simple data processing agent that can transform CSV data

Auto-generated by Dryade Agent Factory.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from core.adapters.protocol import (
    AgentCard,
    AgentFramework,
    AgentResult,
    UniversalAgent,
)
from core.mcp.tool_wrapper import MCPToolWrapper

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def _load_config() -> dict[str, Any]:
    """Load agent configuration from YAML file."""
    config_path = Path(__file__).parent / "config.yaml"
    if config_path.exists():
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {}

# ---------------------------------------------------------------------------
# MCP Tool Wrappers
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Agent Class
# ---------------------------------------------------------------------------

class DataProcessorAgent(UniversalAgent):
    """MCP-native data-processor agent.

    A simple data processing agent that can transform CSV data

    Uses MCPToolWrapper for traced MCP calls without framework overhead.
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        """Initialize the data-processor agent.

        Args:
            config: Optional configuration override. Loaded from config.yaml if not provided.
        """
        self._config = config or _load_config()
        self.name = self._config.get("name", "data-processor")
        self.version = self._config.get("version", "1.0.0")
        self.description = self._config.get(
            "description", "A simple data processing agent that can transform CSV data"
        )

        # Map tool names to wrappers
        self._tools: dict[str, MCPToolWrapper] = {}

    def get_card(self) -> AgentCard:
        """Return agent's capability card.

        Returns:
            AgentCard with framework=MCP and configured capabilities.
        """
        capabilities = []

        return AgentCard(
            name=self.name,
            description=self.description,
            version=self.version,
            framework=AgentFramework.MCP,
            capabilities=capabilities,
            metadata={
                "mcp_servers": [],
            },
        )

    async def execute(
        self,
        task: str,
        context: dict[str, Any] | None = None,
    ) -> AgentResult:
        """Execute a task by routing to appropriate MCP tool(s).

        Analyzes the task string to select the best tool, calls it via
        MCPToolWrapper, and returns the result.

        Args:
            task: Natural language task description.
            context: Optional execution context with additional parameters.

        Returns:
            AgentResult with status and result.
        """
        context = context or {}
        task_lower = task.lower()

        try:
            # Select the best matching tool based on task keywords
            selected_tool = self._select_tool(task_lower)
            if selected_tool is None:
                return AgentResult(
                    result=f"No matching tool found for task: {task}",
                    status="error",
                    error="no_matching_tool",
                    metadata={"agent": self.name},
                )

            result = selected_tool.call(**context)
            return AgentResult(
                result=result,
                status="ok",
                metadata={"agent": self.name, "tool": selected_tool.tool_name},
            )

        except Exception as e:
            logger.error(f"data-processor agent error: {e}")
            return AgentResult(
                result=None,
                status="error",
                error=str(e),
                metadata={"agent": self.name},
            )

    def _select_tool(self, task_lower: str) -> MCPToolWrapper | None:
        """Select the best matching tool for a task.

        Args:
            task_lower: Lowercased task string.

        Returns:
            MCPToolWrapper if a match is found, else None.
        """
        for tool_name, wrapper in self._tools.items():
            if tool_name.replace("_", " ") in task_lower or tool_name in task_lower:
                return wrapper
        # Fallback: return first tool if only one available
        if len(self._tools) == 1:
            return next(iter(self._tools.values()))
        return None

    def get_tools(self) -> list[dict[str, Any]]:
        """Return available tools in OpenAI function format.

        Returns:
            List of tool definitions.
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": name,
                    "description": wrapper.description,
                    "parameters": {"type": "object", "properties": {}},
                },
            }
            for name, wrapper in self._tools.items()
        ]

    def supports_streaming(self) -> bool:
        """This agent does not support streaming."""
        return False

# ---------------------------------------------------------------------------
# Factory function (discovered by zero_dev.py _wrap_custom)
# ---------------------------------------------------------------------------

def create_data_processor_agent(config: dict[str, Any] | None = None) -> DataProcessorAgent:
    """Factory function to create a data-processor agent.

    Args:
        config: Optional configuration override.

    Returns:
        Configured DataProcessorAgent instance.
    """
    return DataProcessorAgent(config=config)

# Alias for zero_dev.py discovery (looks for create_agent)
create_agent = create_data_processor_agent

async def run(task: str, **kwargs) -> str:
    """Entry point declared in dryade.json run_function."""
    agent = create_data_processor_agent()
    result = await agent.execute(task, context=kwargs)
    if result.status == "ok":
        return str(result.result) if result.result is not None else ""
    raise RuntimeError(result.error or "Execution failed")

__all__ = [
    "DataProcessorAgent",
    "create_data_processor_agent",
    "create_agent",
    "run",
]
