"""initial baseline

Revision ID: 2ea81be64492
Revises:
Create Date: 2026-02-19 23:51:00.533876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ea81be64492"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_logs_action", ["action"], unique=False)
        batch_op.create_index("ix_audit_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_audit_logs_user_id", ["user_id"], unique=False)

    op.create_table(
        "cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cache_key_hash"), ["key_hash"], unique=True)

    op.create_table(
        "cost_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("agent", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("template_version_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cost_records", schema=None) as batch_op:
        batch_op.create_index("ix_cost_records_conversation_id", ["conversation_id"], unique=False)
        batch_op.create_index("ix_cost_records_model", ["model"], unique=False)
        batch_op.create_index("ix_cost_records_template_id", ["template_id"], unique=False)
        batch_op.create_index("ix_cost_records_timestamp", ["timestamp"], unique=False)
        batch_op.create_index("ix_cost_records_user_id", ["user_id"], unique=False)

    op.create_table(
        "custom_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("requires_api_key", sa.Boolean(), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_custom_provider_slug"),
    )
    with op.batch_alter_table("custom_providers", schema=None) as batch_op:
        batch_op.create_index("ix_custom_providers_user_id", ["user_id"], unique=False)

    op.create_table(
        "dataset_generations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("output_path", sa.String(length=512), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dataset_generations", schema=None) as batch_op:
        batch_op.create_index("ix_dataset_generations_user_id", ["user_id"], unique=False)

    op.create_table(
        "extension_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=True),
        sa.Column("extension_name", sa.String(length=64), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=True),
        sa.Column("healed", sa.Boolean(), nullable=True),
        sa.Column("threats_found", sa.JSON(), nullable=True),
        sa.Column("validation_errors", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extension_executions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extension_executions_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_extension_executions_request_id"), ["request_id"], unique=False
        )

    op.create_table(
        "extension_timeline",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("extensions_applied", sa.JSON(), nullable=True),
        sa.Column("total_duration_ms", sa.Float(), nullable=False),
        sa.Column("outcomes", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extension_timeline", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extension_timeline_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_extension_timeline_request_id"), ["request_id"], unique=False
        )

    op.create_table(
        "file_operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("threats", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file_operations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_operations_file_path"), ["file_path"], unique=False
        )

    op.create_table(
        "file_scans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("clamav_safe", sa.Boolean(), nullable=True),
        sa.Column("clamav_threats", sa.JSON(), nullable=True),
        sa.Column("yara_safe", sa.Boolean(), nullable=True),
        sa.Column("yara_matches", sa.JSON(), nullable=True),
        sa.Column("scan_time", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file_scans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_scans_file_hash"), ["file_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_scans_file_path"), ["file_path"], unique=False)

    op.create_table(
        "knowledge_sources",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("file_paths", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("crew_ids", sa.JSON(), nullable=False),
        sa.Column("agent_ids", sa.JSON(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "markdown_skills",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("plugin_id", sa.String(length=255), nullable=True),
        sa.Column("skill_dir", sa.String(length=512), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("markdown_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_markdown_skills_name"), ["name"], unique=True)
        batch_op.create_index("ix_markdown_skills_plugin_id", ["plugin_id"], unique=False)

    op.create_table(
        "memory_blocks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("char_limit", sa.Integer(), nullable=True),
        sa.Column("read_only", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_blocks", schema=None) as batch_op:
        batch_op.create_index("ix_memory_blocks_agent_label", ["agent_id", "label"], unique=True)

    op.create_table(
        "model_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("llm_provider", sa.String(length=32), nullable=True),
        sa.Column("llm_model", sa.String(length=128), nullable=True),
        sa.Column("llm_endpoint", sa.String(length=512), nullable=True),
        sa.Column("embedding_provider", sa.String(length=32), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_endpoint", sa.String(length=512), nullable=True),
        sa.Column("asr_provider", sa.String(length=32), nullable=True),
        sa.Column("asr_model", sa.String(length=128), nullable=True),
        sa.Column("asr_endpoint", sa.String(length=512), nullable=True),
        sa.Column("tts_provider", sa.String(length=32), nullable=True),
        sa.Column("tts_model", sa.String(length=128), nullable=True),
        sa.Column("vision_provider", sa.String(length=32), nullable=True),
        sa.Column("vision_model", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("model_configs", schema=None) as batch_op:
        batch_op.create_index("ix_model_configs_user_id", ["user_id"], unique=False)

    op.create_table(
        "model_pricing",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("input_cost_per_token", sa.Float(), nullable=True),
        sa.Column("output_cost_per_token", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_pricing", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_pricing_model_name"), ["model_name"], unique=True
        )
        batch_op.create_index("ix_model_pricing_provider", ["provider"], unique=False)

    op.create_table(
        "optimization_cycles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("metrics_window_start", sa.DateTime(), nullable=False),
        sa.Column("metrics_window_end", sa.DateTime(), nullable=False),
        sa.Column("total_metrics_analyzed", sa.Integer(), nullable=True),
        sa.Column("examples_added", sa.Integer(), nullable=True),
        sa.Column("examples_rejected", sa.Integer(), nullable=True),
        sa.Column("prompt_version_created", sa.String(length=32), nullable=True),
        sa.Column("holdout_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cycle_id"),
    )
    with op.batch_alter_table("optimization_cycles", schema=None) as batch_op:
        batch_op.create_index("ix_optimization_cycles_status", ["status"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("ix_projects_user_id", ["user_id"], unique=False)

    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id", sa.String(length=32), nullable=False),
        sa.Column("prompt_key", sa.String(length=64), nullable=False),
        sa.Column("model_tier", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("optimization_cycle_id", sa.String(length=64), nullable=True),
        sa.Column("parent_version_id", sa.String(length=32), nullable=True),
        sa.Column("metrics_snapshot", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id"),
    )
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.create_index("ix_prompt_versions_active", ["is_active"], unique=False)
        batch_op.create_index(
            "ix_prompt_versions_prompt_key_tier", ["prompt_key", "model_tier"], unique=False
        )

    op.create_table(
        "provider_api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("key_encrypted", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.String(length=8), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=True),
        sa.Column("model_override", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", "model_override", name="uq_provider_key"),
    )
    with op.batch_alter_table("provider_api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_provider_api_keys_user_id", ["user_id"], unique=False)

    op.create_table(
        "resource_shares",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("permission", sa.String(length=16), nullable=True),
        sa.Column("shared_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("permission IN ('view', 'edit')", name="ck_resource_shares_permission"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_type", "resource_id", "user_id", name="uq_resource_share"),
    )
    with op.batch_alter_table("resource_shares", schema=None) as batch_op:
        batch_op.create_index(
            "ix_resource_shares_resource", ["resource_type", "resource_id"], unique=False
        )
        batch_op.create_index("ix_resource_shares_user_id", ["user_id"], unique=False)

    op.create_table(
        "routing_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message_hash", sa.String(length=64), nullable=False),
        sa.Column("hint_fired", sa.Boolean(), nullable=True),
        sa.Column("hint_type", sa.String(length=32), nullable=True),
        sa.Column("llm_tool_called", sa.String(length=64), nullable=True),
        sa.Column("fallback_activated", sa.Boolean(), nullable=True),
        sa.Column("user_approved", sa.Boolean(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tool_arguments_hash", sa.String(length=32), nullable=True),
        sa.Column("success_outcome", sa.Boolean(), nullable=True),
        sa.Column("model_tier_used", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("routing_metrics", schema=None) as batch_op:
        batch_op.create_index("ix_routing_metrics_message_hash", ["message_hash"], unique=False)
        batch_op.create_index("ix_routing_metrics_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "sanitization_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("context", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=128), nullable=True),
        sa.Column("original_length", sa.Integer(), nullable=False),
        sa.Column("sanitized_length", sa.Integer(), nullable=False),
        sa.Column("modifications", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenario_execution_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("scenario_name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("trigger_source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("node_results", sa.JSON(), nullable=True),
        sa.Column("final_result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'cancelled')",
            name="ck_scenario_execution_results_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenario_execution_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_execution_results_execution_id"), ["execution_id"], unique=True
        )
        batch_op.create_index(
            "ix_scenario_execution_results_scenario_name", ["scenario_name"], unique=False
        )
        batch_op.create_index(
            "ix_scenario_execution_results_started_at", ["started_at"], unique=False
        )
        batch_op.create_index("ix_scenario_execution_results_user_id", ["user_id"], unique=False)

    op.create_table(
        "security_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("machine_fingerprint", sa.String(length=12), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("core_version", sa.String(length=20), nullable=True),
        sa.Column("pm_version", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index("ix_security_events_machine", ["machine_fingerprint"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_security_events_machine_fingerprint"),
            ["machine_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_security_events_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            "ix_security_events_type_time", ["event_type", "timestamp"], unique=False
        )

    op.create_table(
        "trained_models",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("model_family", sa.String(length=64), nullable=False),
        sa.Column("base_model", sa.String(length=255), nullable=False),
        sa.Column("adapter_path", sa.String(length=512), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("eval_metrics", sa.JSON(), nullable=True),
        sa.Column("training_job_id", sa.String(length=64), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "version", "user_id", name="uq_trained_models_name_version_user"
        ),
    )
    with op.batch_alter_table("trained_models", schema=None) as batch_op:
        batch_op.create_index("ix_trained_models_user_id", ["user_id"], unique=False)

    op.create_table(
        "training_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("dataset_path", sa.String(length=512), nullable=True),
        sa.Column("output_path", sa.String(length=512), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_training_jobs_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_training_jobs_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "user_invites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invited_by", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("permission", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "permission IN ('view', 'edit', 'owner')", name="ck_user_invites_permission"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'revoked')", name="ck_user_invites_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invited_by", "email", name="uq_user_invites_invited_by_email"),
    )
    with op.batch_alter_table("user_invites", schema=None) as batch_op:
        batch_op.create_index("ix_user_invites_email", ["email"], unique=False)
        batch_op.create_index("ix_user_invites_invited_by", ["invited_by"], unique=False)

    op.create_table(
        "user_notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_notifications", schema=None) as batch_op:
        batch_op.create_index("ix_user_notifications_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_user_notifications_user_read", ["user_id", "is_read"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("is_external", sa.Boolean(), nullable=True),
        sa.Column("external_provider", sa.String(length=64), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_email", ["email"], unique=False)

    op.create_table(
        "validation_failures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_type", sa.String(length=64), nullable=False),
        sa.Column("route", sa.String(length=128), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("workflow_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("execution_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name="ck_workflows_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", "user_id", name="uq_workflows_name_version_user"),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflows_name"), ["name"], unique=False)
        batch_op.create_index("ix_workflows_name_version", ["name", "version"], unique=False)
        batch_op.create_index("ix_workflows_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflows_user_id"), ["user_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("project_id", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "workflow_execution_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("conversation_id", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("node_results", sa.JSON(), nullable=True),
        sa.Column("final_result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("template_version_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed')",
            name="ck_workflow_execution_results_status",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_execution_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workflow_execution_results_conversation_id", ["conversation_id"], unique=False
        )
        batch_op.create_index(
            "ix_workflow_execution_results_template_id", ["template_id"], unique=False
        )
        batch_op.create_index(
            "ix_workflow_execution_results_template_version_id",
            ["template_version_id"],
            unique=False,
        )
        batch_op.create_index("ix_workflow_execution_results_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_workflow_execution_results_workflow_id", ["workflow_id"], unique=False
        )

    op.create_table(
        "checkpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkpoint_id"),
    )
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_checkpoints_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "execution_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("edges", sa.JSON(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'executing', 'completed', 'failed', 'cancelled')",
            name="ck_execution_plans_status",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("execution_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_execution_plans_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_execution_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "plan_execution_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("node_results", sa.JSON(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("user_feedback_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback_comment", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('executing', 'completed', 'failed', 'cancelled', 'timeout')",
            name="ck_plan_execution_results_status",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["execution_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plan_execution_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plan_execution_results_execution_id"), ["execution_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_plan_execution_results_plan_id"), ["plan_id"], unique=False
        )

    op.create_table(
        "tool_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tool_results_message_id"), ["message_id"], unique=False
        )

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_results_message_id"))

    op.drop_table("tool_results")
    with op.batch_alter_table("plan_execution_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_execution_results_plan_id"))
        batch_op.drop_index(batch_op.f("ix_plan_execution_results_execution_id"))

    op.drop_table("plan_execution_results")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("execution_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_plans_user_id"))
        batch_op.drop_index(batch_op.f("ix_execution_plans_conversation_id"))

    op.drop_table("execution_plans")
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checkpoints_conversation_id"))

    op.drop_table("checkpoints")
    with op.batch_alter_table("workflow_execution_results", schema=None) as batch_op:
        batch_op.drop_index("ix_workflow_execution_results_workflow_id")
        batch_op.drop_index("ix_workflow_execution_results_user_id")
        batch_op.drop_index("ix_workflow_execution_results_template_version_id")
        batch_op.drop_index("ix_workflow_execution_results_template_id")
        batch_op.drop_index("ix_workflow_execution_results_conversation_id")

    op.drop_table("workflow_execution_results")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_project_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflows_user_id"))
        batch_op.drop_index("ix_workflows_status")
        batch_op.drop_index("ix_workflows_name_version")
        batch_op.drop_index(batch_op.f("ix_workflows_name"))

    op.drop_table("workflows")
    op.drop_table("validation_failures")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_email")

    op.drop_table("users")
    with op.batch_alter_table("user_notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_user_notifications_user_read")
        batch_op.drop_index("ix_user_notifications_created_at")

    op.drop_table("user_notifications")
    with op.batch_alter_table("user_invites", schema=None) as batch_op:
        batch_op.drop_index("ix_user_invites_invited_by")
        batch_op.drop_index("ix_user_invites_email")

    op.drop_table("user_invites")
    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_training_jobs_user_status")
        batch_op.drop_index(batch_op.f("ix_training_jobs_user_id"))

    op.drop_table("training_jobs")
    with op.batch_alter_table("trained_models", schema=None) as batch_op:
        batch_op.drop_index("ix_trained_models_user_id")

    op.drop_table("trained_models")
    with op.batch_alter_table("security_events", schema=None) as batch_op:
        batch_op.drop_index("ix_security_events_type_time")
        batch_op.drop_index(batch_op.f("ix_security_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_security_events_machine_fingerprint"))
        batch_op.drop_index("ix_security_events_machine")
        batch_op.drop_index(batch_op.f("ix_security_events_event_type"))

    op.drop_table("security_events")
    with op.batch_alter_table("scenario_execution_results", schema=None) as batch_op:
        batch_op.drop_index("ix_scenario_execution_results_user_id")
        batch_op.drop_index("ix_scenario_execution_results_started_at")
        batch_op.drop_index("ix_scenario_execution_results_scenario_name")
        batch_op.drop_index(batch_op.f("ix_scenario_execution_results_execution_id"))

    op.drop_table("scenario_execution_results")
    op.drop_table("sanitization_events")
    with op.batch_alter_table("routing_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_routing_metrics_timestamp")
        batch_op.drop_index("ix_routing_metrics_message_hash")

    op.drop_table("routing_metrics")
    with op.batch_alter_table("resource_shares", schema=None) as batch_op:
        batch_op.drop_index("ix_resource_shares_user_id")
        batch_op.drop_index("ix_resource_shares_resource")

    op.drop_table("resource_shares")
    with op.batch_alter_table("provider_api_keys", schema=None) as batch_op:
        batch_op.drop_index("ix_provider_api_keys_user_id")

    op.drop_table("provider_api_keys")
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_prompt_versions_prompt_key_tier")
        batch_op.drop_index("ix_prompt_versions_active")

    op.drop_table("prompt_versions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_user_id")

    op.drop_table("projects")
    with op.batch_alter_table("optimization_cycles", schema=None) as batch_op:
        batch_op.drop_index("ix_optimization_cycles_status")

    op.drop_table("optimization_cycles")
    with op.batch_alter_table("model_pricing", schema=None) as batch_op:
        batch_op.drop_index("ix_model_pricing_provider")
        batch_op.drop_index(batch_op.f("ix_model_pricing_model_name"))

    op.drop_table("model_pricing")
    with op.batch_alter_table("model_configs", schema=None) as batch_op:
        batch_op.drop_index("ix_model_configs_user_id")

    op.drop_table("model_configs")
    with op.batch_alter_table("memory_blocks", schema=None) as batch_op:
        batch_op.drop_index("ix_memory_blocks_agent_label")

    op.drop_table("memory_blocks")
    with op.batch_alter_table("markdown_skills", schema=None) as batch_op:
        batch_op.drop_index("ix_markdown_skills_plugin_id")
        batch_op.drop_index(batch_op.f("ix_markdown_skills_name"))

    op.drop_table("markdown_skills")
    op.drop_table("knowledge_sources")
    with op.batch_alter_table("file_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_scans_file_path"))
        batch_op.drop_index(batch_op.f("ix_file_scans_file_hash"))

    op.drop_table("file_scans")
    with op.batch_alter_table("file_operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_operations_file_path"))

    op.drop_table("file_operations")
    with op.batch_alter_table("extension_timeline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extension_timeline_request_id"))
        batch_op.drop_index(batch_op.f("ix_extension_timeline_conversation_id"))

    op.drop_table("extension_timeline")
    with op.batch_alter_table("extension_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extension_executions_request_id"))
        batch_op.drop_index(batch_op.f("ix_extension_executions_conversation_id"))

    op.drop_table("extension_executions")
    with op.batch_alter_table("dataset_generations", schema=None) as batch_op:
        batch_op.drop_index("ix_dataset_generations_user_id")

    op.drop_table("dataset_generations")
    with op.batch_alter_table("custom_providers", schema=None) as batch_op:
        batch_op.drop_index("ix_custom_providers_user_id")

    op.drop_table("custom_providers")
    with op.batch_alter_table("cost_records", schema=None) as batch_op:
        batch_op.drop_index("ix_cost_records_user_id")
        batch_op.drop_index("ix_cost_records_timestamp")
        batch_op.drop_index("ix_cost_records_template_id")
        batch_op.drop_index("ix_cost_records_model")
        batch_op.drop_index("ix_cost_records_conversation_id")

    op.drop_table("cost_records")
    with op.batch_alter_table("cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cache_key_hash"))

    op.drop_table("cache")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_user_id")
        batch_op.drop_index("ix_audit_logs_created_at")
        batch_op.drop_index("ix_audit_logs_action")

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
