"""meeting_summarizer - ADK Agent.

Meeting intelligence agent that processes audio transcripts, extracts key decisions and action items, identifies owners and deadlines, and distributes structured summaries to attendees via their preferred channels.

Auto-generated by Dryade Agent Factory.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from core.mcp.tool_wrapper import MCPToolWrapper

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def _load_config() -> dict[str, Any]:
    """Load agent configuration from YAML file."""
    config_path = Path(__file__).parent / "config.yaml"
    if config_path.exists():
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {}

# ---------------------------------------------------------------------------
# MCP Tool Wrappers
# ---------------------------------------------------------------------------

_fetch_calendar_events_wrapper = MCPToolWrapper(
    "google-calendar-mcp-server",
    "fetch_calendar_events",
    "Fetch calendar events and meeting metadata",
)
_post_summary_wrapper = MCPToolWrapper(
    "slack-mcp-server", "post_summary", "Post meeting summary to Slack channel"
)
_create_page_wrapper = MCPToolWrapper(
    "notion-mcp-server", "create_page", "Create Notion page with structured meeting notes"
)
_update_action_tracker_wrapper = MCPToolWrapper(
    "notion-mcp-server",
    "update_action_tracker",
    "Update action item tracker with assignments and deadlines",
)

# ---------------------------------------------------------------------------
# ADK Tool Adapters
# ---------------------------------------------------------------------------

def _create_adk_tools() -> list:
    """Create ADK FunctionTool wrappers for each MCP tool.

    Returns:
        List of ADK FunctionTool instances, or empty list if ADK not installed.
    """
    try:
        from google.adk.tools import FunctionTool
    except ImportError:
        logger.warning("google-adk not installed; returning empty tool list")
        return []

    tools = []

    def _invoke_fetch_calendar_events(**kwargs: Any) -> str:
        """Fetch calendar events and meeting metadata"""
        return _fetch_calendar_events_wrapper.call(**kwargs)

    tools.append(FunctionTool(_invoke_fetch_calendar_events))

    def _invoke_post_summary(**kwargs: Any) -> str:
        """Post meeting summary to Slack channel"""
        return _post_summary_wrapper.call(**kwargs)

    tools.append(FunctionTool(_invoke_post_summary))

    def _invoke_create_page(**kwargs: Any) -> str:
        """Create Notion page with structured meeting notes"""
        return _create_page_wrapper.call(**kwargs)

    tools.append(FunctionTool(_invoke_create_page))

    def _invoke_update_action_tracker(**kwargs: Any) -> str:
        """Update action item tracker with assignments and deadlines"""
        return _update_action_tracker_wrapper.call(**kwargs)

    tools.append(FunctionTool(_invoke_update_action_tracker))

    return tools

# ---------------------------------------------------------------------------
# Factory function (discovered by zero_dev.py _wrap_adk)
# ---------------------------------------------------------------------------

root_agent = None

def create_agent(config: dict[str, Any] | None = None) -> Any:
    """Create and return an ADK LlmAgent.

    Args:
        config: Optional configuration override.

    Returns:
        google.adk.agents.LlmAgent instance.
    """
    global root_agent

    try:
        from google.adk.agents import LlmAgent
    except ImportError as exc:
        raise ImportError(
            "google-adk is required for ADK agents. Install with: pip install google-adk"
        ) from exc

    cfg = config or _load_config()
    tools = _create_adk_tools()

    # Model can be configured via Dryade's LLM settings
    agent = LlmAgent(
        model=cfg.get("model", "gemini-2.0-flash"),
        name="meeting_summarizer",
        instruction="Transform meeting transcripts into structured, actionable summaries with clear decisions, owners, and deadlines that keep teams aligned and accountable",
        tools=tools,
    )

    root_agent = agent
    return agent

async def run(task: str, **kwargs) -> str:
    """Entry point declared in dryade.json run_function."""
    agent = create_agent()
    try:
        from google.adk.runners import Runner
        from google.adk.sessions import InMemorySessionService

        runner = Runner(
            agent=agent, app_name="meeting_summarizer", session_service=InMemorySessionService()
        )
        session = await runner.session_service.create_session(
            app_name="meeting_summarizer", user_id="factory"
        )
        from google.genai import types

        content = types.Content(role="user", parts=[types.Part(text=task)])
        response_parts = []
        async for event in runner.run(
            user_id="factory", session_id=session.id, new_message=content
        ):
            if event.is_final_response() and event.content and event.content.parts:
                response_parts.extend(p.text for p in event.content.parts if p.text)
        return "".join(response_parts) if response_parts else ""
    except ImportError:
        raise RuntimeError("google-adk is required. Install with: pip install google-adk")

__all__ = ["create_agent", "run"]
